[hyprwinwrap]
description = "A clone of xwinwrap for Hyprland"
version = "1.0"
authors = ["Vaxry, OnlyMikey"]

[hyprwinwrap.build]
output = "hyprwinwrap/hyprwinwrap.so"
steps = [
    "make -C hyprwinwrap all",
]
